version: '3.4'

networks:
  l01:
    driver: bridge 

services:
  lanchonete-service:
    image: ${REGISTRY:-service-one}/customer-service.api:${PLATFORM:-linux}-${TAG:-latest}
    depends_on:
      - "tech_challenge_db"
    container_name: lanchonete-service
    ports:
      - "5009:80"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionString=host=tech_challenge_db;port=5432;database=lanchonete;username=postgres;password=postgres;Pooling=true;
    networks:
      - l01

  tech_challenge_db:
    image: postgres:latest
    container_name: tech_challenge_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lanchonete
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - customer_data:/var/lib/postgresql/data/ 
    networks:
      - l01

volumes:
  lanchonete_data:
