# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  techchallenge:
    image: techchallenge
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - configuration=Debug
    ports:
      - 4005:4005
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:4005
      - ASPNETCORE_HTTP_PORTS=4005
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
