# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  techchallenge:
    image: techchallenge
    depends_on:
      - "techchallenge_db"
    container_name: lanchonete-service
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    environment:
      - ConnectionString=host=techchallenge_db;port=5432;database=tech_challenge;username=postgres;password=mysecretpassword;Pooling=true;
    networks:
      - l01

  techchallenge_db:
    image: postgres:latest
    container_name: techchallenge_db
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/ 
    networks:
      - l01

volumes:
  postgres_data:

networks: 
  l01: